[package]
name = "pltrs_backend_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
pltrs_core = { path = "../pltrs_core" }
winit = "0.30"
wgpu = "0.20"
env_logger = "0.11"
pollster = "0.3"
anyhow = "1.0.100"
